-- Slovenia Municipalities Seed Data
-- Slovenia has 212 municipalities as of 2024

-- Insert Slovenia
INSERT INTO countries (name, code, municipality_count) VALUES ('Slovenia', 'SI', 212);

-- Insert all 212 Slovenian municipalities
-- Audio file naming convention: si-{municipality-name-lowercase}.mp3

INSERT INTO municipalities (name, country_id, audio_file) VALUES
-- A
('Ajdovščina', 1, 'si-ajdovscina.mp3'),
('Ankaran', 1, 'si-ankaran.mp3'),
('Apače', 1, 'si-apace.mp3'),
-- B
('Beltinci', 1, 'si-beltinci.mp3'),
('Benedikt', 1, 'si-benedikt.mp3'),
('Bistrica ob Sotli', 1, 'si-bistrica-ob-sotli.mp3'),
('Bled', 1, 'si-bled.mp3'),
('Bloke', 1, 'si-bloke.mp3'),
('Bohinj', 1, 'si-bohinj.mp3'),
('Borovnica', 1, 'si-borovnica.mp3'),
('Bovec', 1, 'si-bovec.mp3'),
('Braslovče', 1, 'si-braslovce.mp3'),
('Brda', 1, 'si-brda.mp3'),
('Brezovica', 1, 'si-brezovica.mp3'),
('Brežice', 1, 'si-brezice.mp3'),
('Cankova', 1, 'si-cankova.mp3'),
-- C
('Celje', 1, 'si-celje.mp3'),
('Cerklje na Gorenjskem', 1, 'si-cerklje-na-gorenjskem.mp3'),
('Cerknica', 1, 'si-cerknica.mp3'),
('Cerkno', 1, 'si-cerkno.mp3'),
('Cerkvenjak', 1, 'si-cerkvenjak.mp3'),
('Cirkulane', 1, 'si-cirkulane.mp3'),
('Črenšovci', 1, 'si-crensovci.mp3'),
('Črna na Koroškem', 1, 'si-crna-na-koroskem.mp3'),
('Črnomelj', 1, 'si-crnomelj.mp3'),
-- D
('Destrnik', 1, 'si-destrnik.mp3'),
('Divača', 1, 'si-divaca.mp3'),
('Dobje', 1, 'si-dobje.mp3'),
('Dobrepolje', 1, 'si-dobrepolje.mp3'),
('Dobrna', 1, 'si-dobrna.mp3'),
('Dobrova-Polhov Gradec', 1, 'si-dobrova-polhov-gradec.mp3'),
('Dobrovnik', 1, 'si-dobrovnik.mp3'),
('Dol pri Ljubljani', 1, 'si-dol-pri-ljubljani.mp3'),
('Dolenjske Toplice', 1, 'si-dolenjske-toplice.mp3'),
('Domžale', 1, 'si-domzale.mp3'),
('Dornava', 1, 'si-dornava.mp3'),
('Dravograd', 1, 'si-dravograd.mp3'),
('Duplek', 1, 'si-duplek.mp3'),
-- G
('Gorenja vas-Poljane', 1, 'si-gorenja-vas-poljane.mp3'),
('Gorišnica', 1, 'si-gorisnica.mp3'),
('Gorje', 1, 'si-gorje.mp3'),
('Gornja Radgona', 1, 'si-gornja-radgona.mp3'),
('Gornji Grad', 1, 'si-gornji-grad.mp3'),
('Gornji Petrovci', 1, 'si-gornji-petrovci.mp3'),
('Grad', 1, 'si-grad.mp3'),
('Grosuplje', 1, 'si-grosuplje.mp3'),
-- H
('Hajdina', 1, 'si-hajdina.mp3'),
('Hoče-Slivnica', 1, 'si-hoce-slivnica.mp3'),
('Hodoš', 1, 'si-hodos.mp3'),
('Horjul', 1, 'si-horjul.mp3'),
('Hrastnik', 1, 'si-hrastnik.mp3'),
('Hrpelje-Kozina', 1, 'si-hrpelje-kozina.mp3'),
-- I
('Idrija', 1, 'si-idrija.mp3'),
('Ig', 1, 'si-ig.mp3'),
('Ilirska Bistrica', 1, 'si-ilirska-bistrica.mp3'),
('Ivančna Gorica', 1, 'si-ivancna-gorica.mp3'),
('Izola', 1, 'si-izola.mp3'),
-- J
('Jesenice', 1, 'si-jesenice.mp3'),
('Jezersko', 1, 'si-jezersko.mp3'),
('Juršinci', 1, 'si-jursinci.mp3'),
-- K
('Kamnik', 1, 'si-kamnik.mp3'),
('Kanal ob Soči', 1, 'si-kanal-ob-soci.mp3'),
('Kidričevo', 1, 'si-kidricevo.mp3'),
('Kobarid', 1, 'si-kobarid.mp3'),
('Kobilje', 1, 'si-kobilje.mp3'),
('Kočevje', 1, 'si-kocevje.mp3'),
('Komen', 1, 'si-komen.mp3'),
('Komenda', 1, 'si-komenda.mp3'),
('Koper', 1, 'si-koper.mp3'),
('Kostanjevica na Krki', 1, 'si-kostanjevica-na-krki.mp3'),
('Kostel', 1, 'si-kostel.mp3'),
('Kozje', 1, 'si-kozje.mp3'),
('Kranj', 1, 'si-kranj.mp3'),
('Kranjska Gora', 1, 'si-kranjska-gora.mp3'),
('Križevci', 1, 'si-krizevci.mp3'),
('Krško', 1, 'si-krsko.mp3'),
('Kungota', 1, 'si-kungota.mp3'),
('Kuzma', 1, 'si-kuzma.mp3'),
-- L
('Laško', 1, 'si-lasko.mp3'),
('Lenart', 1, 'si-lenart.mp3'),
('Lendava', 1, 'si-lendava.mp3'),
('Litija', 1, 'si-litija.mp3'),
('Ljubljana', 1, 'si-ljubljana.mp3'),
('Ljubno', 1, 'si-ljubno.mp3'),
('Ljutomer', 1, 'si-ljutomer.mp3'),
('Log-Dragomer', 1, 'si-log-dragomer.mp3'),
('Logatec', 1, 'si-logatec.mp3'),
('Loška dolina', 1, 'si-loska-dolina.mp3'),
('Loški Potok', 1, 'si-loski-potok.mp3'),
('Lovrenc na Pohorju', 1, 'si-lovrenc-na-pohorju.mp3'),
('Luče', 1, 'si-luce.mp3'),
('Lukovica', 1, 'si-lukovica.mp3'),
-- M
('Majšperk', 1, 'si-majsperk.mp3'),
('Makole', 1, 'si-makole.mp3'),
('Maribor', 1, 'si-maribor.mp3'),
('Markovci', 1, 'si-markovci.mp3'),
('Medvode', 1, 'si-medvode.mp3'),
('Mengeš', 1, 'si-menges.mp3'),
('Metlika', 1, 'si-metlika.mp3'),
('Mežica', 1, 'si-mezica.mp3'),
('Miklavž na Dravskem polju', 1, 'si-miklavz-na-dravskem-polju.mp3'),
('Miren-Kostanjevica', 1, 'si-miren-kostanjevica.mp3'),
('Mirna', 1, 'si-mirna.mp3'),
('Mirna Peč', 1, 'si-mirna-pec.mp3'),
('Mislinja', 1, 'si-mislinja.mp3'),
('Mokronog-Trebelno', 1, 'si-mokronog-trebelno.mp3'),
('Moravče', 1, 'si-moravce.mp3'),
('Moravske Toplice', 1, 'si-moravske-toplice.mp3'),
('Mozirje', 1, 'si-mozirje.mp3'),
('Murska Sobota', 1, 'si-murska-sobota.mp3'),
('Muta', 1, 'si-muta.mp3'),
-- N
('Naklo', 1, 'si-naklo.mp3'),
('Nazarje', 1, 'si-nazarje.mp3'),
('Nova Gorica', 1, 'si-nova-gorica.mp3'),
('Novo mesto', 1, 'si-novo-mesto.mp3'),
-- O
('Odranci', 1, 'si-odranci.mp3'),
('Oplotnica', 1, 'si-oplotnica.mp3'),
('Ormož', 1, 'si-ormoz.mp3'),
('Osilnica', 1, 'si-osilnica.mp3'),
-- P
('Pesnica', 1, 'si-pesnica.mp3'),
('Piran', 1, 'si-piran.mp3'),
('Pivka', 1, 'si-pivka.mp3'),
('Podčetrtek', 1, 'si-podcetrtek.mp3'),
('Podlehnik', 1, 'si-podlehnik.mp3'),
('Podvelka', 1, 'si-podvelka.mp3'),
('Poljčane', 1, 'si-poljcane.mp3'),
('Polzela', 1, 'si-polzela.mp3'),
('Postojna', 1, 'si-postojna.mp3'),
('Prebold', 1, 'si-prebold.mp3'),
('Preddvor', 1, 'si-preddvor.mp3'),
('Prevalje', 1, 'si-prevalje.mp3'),
('Ptuj', 1, 'si-ptuj.mp3'),
('Puconci', 1, 'si-puconci.mp3'),
-- R
('Rače-Fram', 1, 'si-race-fram.mp3'),
('Radeče', 1, 'si-radece.mp3'),
('Radenci', 1, 'si-radenci.mp3'),
('Radlje ob Dravi', 1, 'si-radlje-ob-dravi.mp3'),
('Radovljica', 1, 'si-radovljica.mp3'),
('Ravne na Koroškem', 1, 'si-ravne-na-koroskem.mp3'),
('Razkrižje', 1, 'si-razkrizje.mp3'),
('Rečica ob Savinji', 1, 'si-recica-ob-savinji.mp3'),
('Renče-Vogrsko', 1, 'si-rence-vogrsko.mp3'),
('Ribnica', 1, 'si-ribnica.mp3'),
('Ribnica na Pohorju', 1, 'si-ribnica-na-pohorju.mp3'),
('Rogaška Slatina', 1, 'si-rogaska-slatina.mp3'),
('Rogašovci', 1, 'si-rogasovci.mp3'),
('Rogatec', 1, 'si-rogatec.mp3'),
('Ruše', 1, 'si-ruse.mp3'),
-- S
('Selnica ob Dravi', 1, 'si-selnica-ob-dravi.mp3'),
('Semič', 1, 'si-semic.mp3'),
('Sevnica', 1, 'si-sevnica.mp3'),
('Sežana', 1, 'si-sezana.mp3'),
('Slovenj Gradec', 1, 'si-slovenj-gradec.mp3'),
('Slovenska Bistrica', 1, 'si-slovenska-bistrica.mp3'),
('Slovenske Konjice', 1, 'si-slovenske-konjice.mp3'),
('Sodražica', 1, 'si-sodrazica.mp3'),
('Solčava', 1, 'si-solcava.mp3'),
('Središče ob Dravi', 1, 'si-sredisce-ob-dravi.mp3'),
('Starše', 1, 'si-starse.mp3'),
('Straža', 1, 'si-straza.mp3'),
('Sveta Ana', 1, 'si-sveta-ana.mp3'),
('Sveta Trojica v Slovenskih goricah', 1, 'si-sveta-trojica-v-slovenskih-goricah.mp3'),
('Sveti Andraž v Slovenskih goricah', 1, 'si-sveti-andraz-v-slovenskih-goricah.mp3'),
('Sveti Jurij ob Ščavnici', 1, 'si-sveti-jurij-ob-scavnici.mp3'),
('Sveti Jurij v Slovenskih goricah', 1, 'si-sveti-jurij-v-slovenskih-goricah.mp3'),
('Sveti Tomaž', 1, 'si-sveti-tomaz.mp3'),
('Šalovci', 1, 'si-salovci.mp3'),
('Šempeter-Vrtojba', 1, 'si-sempeter-vrtojba.mp3'),
('Šenčur', 1, 'si-sencur.mp3'),
('Šentilj', 1, 'si-sentilj.mp3'),
('Šentjernej', 1, 'si-sentjernej.mp3'),
('Šentjur', 1, 'si-sentjur.mp3'),
('Šentrupert', 1, 'si-sentrupert.mp3'),
('Škocjan', 1, 'si-skocjan.mp3'),
('Škofja Loka', 1, 'si-skofja-loka.mp3'),
('Škofljica', 1, 'si-skofljica.mp3'),
('Šmarje pri Jelšah', 1, 'si-smarje-pri-jelsah.mp3'),
('Šmarješke Toplice', 1, 'si-smarjeske-toplice.mp3'),
('Šmartno ob Paki', 1, 'si-smartno-ob-paki.mp3'),
('Šmartno pri Litiji', 1, 'si-smartno-pri-litiji.mp3'),
('Šoštanj', 1, 'si-sostanj.mp3'),
('Štore', 1, 'si-store.mp3'),
-- T
('Tabor', 1, 'si-tabor.mp3'),
('Tišina', 1, 'si-tisina.mp3'),
('Tolmin', 1, 'si-tolmin.mp3'),
('Trbovlje', 1, 'si-trbovlje.mp3'),
('Trebnje', 1, 'si-trebnje.mp3'),
('Trnovska vas', 1, 'si-trnovska-vas.mp3'),
('Trzin', 1, 'si-trzin.mp3'),
('Tržič', 1, 'si-trzic.mp3'),
('Turnišče', 1, 'si-turnisce.mp3'),
-- V
('Velenje', 1, 'si-velenje.mp3'),
('Velika Polana', 1, 'si-velika-polana.mp3'),
('Velike Lašče', 1, 'si-velike-lasce.mp3'),
('Veržej', 1, 'si-verzej.mp3'),
('Videm', 1, 'si-videm.mp3'),
('Vipava', 1, 'si-vipava.mp3'),
('Vitanje', 1, 'si-vitanje.mp3'),
('Vodice', 1, 'si-vodice.mp3'),
('Vojnik', 1, 'si-vojnik.mp3'),
('Vransko', 1, 'si-vransko.mp3'),
('Vrhnika', 1, 'si-vrhnika.mp3'),
('Vuzenica', 1, 'si-vuzenica.mp3'),
-- Z
('Zagorje ob Savi', 1, 'si-zagorje-ob-savi.mp3'),
('Zavrč', 1, 'si-zavrc.mp3'),
('Zreče', 1, 'si-zrece.mp3'),
-- Ž
('Žalec', 1, 'si-zalec.mp3'),
('Železniki', 1, 'si-zelezniki.mp3'),
('Žetale', 1, 'si-zetale.mp3'),
('Žiri', 1, 'si-ziri.mp3'),
('Žirovnica', 1, 'si-zirovnica.mp3'),
('Žužemberk', 1, 'si-zuzemberk.mp3');

-- Initialize user_progress for all municipalities
INSERT INTO user_progress (municipality_id, next_review)
SELECT id, NOW() FROM municipalities;

-- Initialize today's stats
INSERT INTO daily_stats (date, questions_answered, correct_answers)
VALUES (CURRENT_DATE, 0, 0)
ON CONFLICT (date) DO NOTHING;
